"""empty message

Revision ID: 90fbfa0ae6b4
Revises: b77d8758a35b
Create Date: 2022-05-04 20:48:08.272216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fbfa0ae6b4'
down_revision = 'b77d8758a35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_last_name'), 'user_access', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_access_user_email'), 'user_access', ['user_email'], unique=False)
    op.create_index(op.f('ix_user_access_user_name'), 'user_access', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_access_user_name'), table_name='user_access')
    op.drop_index(op.f('ix_user_access_user_email'), table_name='user_access')
    op.drop_index(op.f('ix_user_access_last_name'), table_name='user_access')
    op.drop_table('user_access')
    # ### end Alembic commands ###
